/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.bfg.domain.model

sealed trait BetfairRequest {
  /* The operation type */
  def op: RequestType
  /* Client generated unique id to link request with response (like json rpc) */
  def id: Int
}

final case class RequestAuthentication(
                                   op: RequestType = Authentication,
                                   id: Int,
                                   session: Session,
                                   appKey: AppKey
) extends BetfairRequest

final case class RequestMarketSubscription (
                                       /* The operation type */
                                       op: String = "marketSubscription",
                                       /* Client generated unique id to link request with response (like json rpc) */
                                       id: Int,
                                       /* Segmentation Enabled - allow the server to send large sets of data in segments, instead of a single block */
                                       segmentationEnabled: Option[Boolean] = None,
                                       /* Token value delta (received in MarketChangeMessage) that should be passed to resume a subscription */
                                       clk: Option[String] = None,
                                       /* Heartbeat Milliseconds - the heartbeat rate (looped back on initial image after validation: bounds are 500 to 5000) */
                                       heartbeatMs: Option[Long] = None,
                                       /* Token value (received in initial MarketChangeMessage) that should be passed to resume a subscription */
                                       initialClk: Option[String] = None,
                                       marketFilter: MarketSubscriptionMarketFilter,
                                       /* Conflate Milliseconds - the conflation rate (looped back on initial image after validation: bounds are 0 to 120000) */
                                       conflateMs: Option[Long] = None,
                                       marketDataFilter: MarketSubscriptionMarketDataFilter
                                     ) extends BetfairRequest

final case class MarketSubscriptionMarketFilter(
                                                   countryCodes: List[String],
                                                   bettingTypes: Option[List[String]] = None,
                                                   turnInPlayEnabled: Option[Boolean] = None,
                                                   marketTypes: List[String],
                                                   venues: Option[List[String]] = None,
                                                   marketIds: Option[List[String]] = None,
                                                   eventTypeIds: List[String],
                                                   eventIds: Option[List[String]] = None,
                                                   bspMarket: Option[Boolean] = None
                                                 )

case class MarketSubscriptionMarketDataFilter(ladderLevels: Option[Int] = None,
                                              fields: List[String])
